version: '3.5'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'SUPER_DUPER_MARKET'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: