spring:
  application:
    name: product-management-solution
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SUPER_DUPER_MARKET?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
product-management:
  interactive-mode: true
  time-period: 20
  csv-file-path: product-management-solution/src/main/resources/products.csv
  fish-is-active: true
  csv-import-active: true
  sql-import-active: false
